### PR TITLE
sync string definition to fix bug skip space, TODO: escape char

### PR DESCRIPTION
**Pull request by thomasyonug**

### CODE REVIEW

**Comment by diaozhongpu** [comment]
I am wondering in what case a WHITESPACE constitutes a legitimate STRING?

**Comment by thomasyonug** [comment]
> I am wondering in what case a WHITESPACE constitutes a legitimate STRING?

Consider about a space char between hello and world in "hello world" ?

**Comment by diaozhongpu** [comment]
The lexer rule for quoted string like "hello world‘ is `QUOTED_STRING` in line 97, not `STRING` in 95. Consider use
```
QUOTED_STRING:
	DOUBLE_QUOTE ( LETTER_WHEN_UNQUOTED | WHITESPACE )+ DOUBLE_QUOTE
;
```

btw, `STRING` is a fragment rule to define `IDENTIFIER`, not for string variables.

**Comment by thomasyonug** [comment]
> The lexer rule for quoted string like "hello world‘ is `QUOTED_STRING` in line 97, not `STRING` in 95. Consider use
> 
> ```
> QUOTED_STRING:
> 	DOUBLE_QUOTE ( LETTER_WHEN_UNQUOTED | WHITESPACE )+ DOUBLE_QUOTE
> ;
> ```
> 
> btw, `STRING` is a fragment rule to define `IDENTIFIER`, not for string variables.

ok,fixed

**Pull request merged**
